config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end
  resources :projects, only: [:index, :show, :edit, :update] do
        resources :tickets
   end
  devise_for :users
  

end

app/models/project.rb
class Project < ActiveRecord::Base
	  validates :name, presence: true
	  #validates :description , presence: true
	  has_many :tickets , dependent: :delete_all
	
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :projects
  belongs_to :author, class_name: "User"
  validates :name, presence: true
  validates :description, presence: true  ,length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
	  before_action :authorize_admin!
  def index
  end

  private
     def authorize_admin!
         authenticate_user!
         unless current_user.admin?
         redirect_to root_path, alert: "You must be an admin to do that."
      end
    end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
     
      def new
         @project = Project.new
      end

      def create
          @project = Project.new(project_params)
      if @project.save
          flash[:notice] = "Project has been created."
          redirect_to @project
       else
          flash.now[:alert] = "Project has not been created."
          render "new"
         end
       end

      def destroy
          @project.destroy
          flash[:notice] = "Project has been deleted."
          redirect_to projects_path
      end

  private
         def project_params
             params.require(:project).permit(:name, :description)
     end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
     # before_filter :initialize_user

  #def initialize_user
       #@user = User.new
  #end


  def index
      @user = User.order(:email)
  end

  def new
  	  @user = User.new
  end	

  def create
      @user = User.new(user_params)
      if @user.save
         flash[:notice] = "User has been created."
         redirect_to admin_users_path
      else
         flash.now[:alert] = "User has not been created."
         render "new"
      end
  end

private
  
  def user_params
       params.require(:user).permit(:email, :password, :admin)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
      before_action :set_project, only: [:show, :edit, :update, :destroy]
      
      def index
         @projects = Project.all
      end	
      
      def new
      	 @project = Project.new
      end	

      def edit
        @project = Project.find(params[:id])
      end

      def create
          @project = Project.new(project_params)
          if @project.save
             flash[:notice] = "Project has been created."
             redirect_to @project
          else
          	   flash.now[:alert] = "Project has not been created."
               render "new"
          end
       end

      def show
          @project = Project.find(params[:id])
      end

       def update
          @project = Project.find(params[:id])
       if @project.update(project_params)
            flash[:notice] = "Project has been updated."
            redirect_to @project
       else
            flash[:alert] = "Project has not been updated."
            render 'edit'   
     end
   end 


      def destroy
         @project = Project.find(params[:id])
         @project.destroy
         flash[:notice] = "Project has been deleted."
          redirect_to projects_path
      end
      

      def set_project
          @project = Project.find(params[:id])
          rescue ActiveRecord::RecordNotFound
          flash[:alert] = "The project you were looking for could not be found."
          redirect_to projects_path
      end  
      
     private
         def project_params
             params.require(:project).permit(:name, :description)
         end  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	    before_action :set_project
      before_action :set_ticket, only: [:show, :edit, :update, :destroy]

      def new
         @ticket = @project.tickets.build
      end
      
      def create
          @ticket = @project.tickets.build(ticket_params)
          @ticket.author = current_user
          if @ticket.save
             flash[:notice] = "Ticket has been created."
             redirect_to [@project, @ticket]
          else
             flash.now[:alert] = "Ticket has not been created."
             render "new"
          end
       end


       def show
       end

       def edit
       end

       def update
          if @ticket.update(ticket_params)
             flash[:notice] = "Ticket has been updated."
             redirect_to [@project, @ticket]
          else
             flash.now[:alert] = "Ticket has not been updated."
             render "edit" 
            end
        end
    
        def destroy
            @ticket.destroy
            flash[:notice] = "Ticket has been deleted."
            redirect_to @project
         end
       

private
    
      def set_project 
         @project = Project.find(params[:project_id])
    end
    def set_ticket
           @ticket = @project.tickets.find(params[:id])
    end
    def ticket_params
        params.require(:ticket).permit(:name, :description)
   end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(*parts)
        unless parts.empty?
        content_for :title do
        (parts << "Ticketee").join(" - ")
     end     
   end
  end
  def admins_only(&block)
         block.call if current_user.try(:admin?)
     end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/application/index.html.erb
<div class="container" id="admin">

  <div class="content row">
   <div id="title"><h1>Admin Lounge</h1></div>
   <p>Welcome to Ticketee's Admin Lounge. Please enjoy your stay.</p>
</div>

<div class="sidebar row">
	<h2>Admin Links</h2>
        <ul class="nav nav-stacked">
          <li><%= link_to "Users", admin_users_path %></li>
        </ul>
</div>


</div><!-- container -->

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, project]) do |f| %>
 <% if project.errors.any? %>
    <div id="error_explanation">
              <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
       <ul>
           <% project.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
       </ul>
    </div>
<% end %>

<div class='label'>
           	 <%= f.label :name %>
           </div><!-- label -->

           <div id="prject_name_input">
                <%= f.text_field :name %>
           </div><!-- project_name input-->
       </div><!--project name-->

       <div id="description">
            <div class="label">
                <%= f.label :description %>
            </div><!-- description -->
            <div id="description_input">
                <%= f.text_field :description  %>
            </div><!-- description input -->

       </div><!-- description -->
      
    <div id="submit" >
       <%= f.submit %>
   </div><!-- submit -->
    
    
 
<% end %>

app/views/admin/projects/new.html.erb
<% title(@project.name, "Create New Project") %>

<div class="container">
    <% if @project.errors.any? %>
           <div id="error_explanation">
           <h2><%= pluralize(@project.errors.count, "error") %>
                   prohibited this project from being saved:</h2>
            <ul>
                <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
          </div>
     <% end %>
     
<div class=" information_holder ">
    	<h2>Create New Project </h2>
    	<p id="title">
           Start your new project here. 
    	</p>

       <%= form_for(@project)  do |f| %>
       <div id="project_name">
           <div class='label'>
           	 <%= f.label :name %>
           </div><!-- label -->

           <div id="prject_name_input">
                <%= f.text_field :name , :placeholder =>"Project Name"%>
           </div><!-- project_name input-->
       </div><!--project name-->

       <div id="description">
            <div class="label">
                <%= f.label :description %>
            </div><!-- description -->
            <div id="description_input">
                <%= f.text_field :description , :placeholder =>"Project  Description" %>
            </div><!-- description input -->

       </div><!-- description -->

       <div id="submit">
           <%= f.submit %>
       </div><!-- submit -->

       

    <% end %>
    </div><!-- information_holder -->


</div><!-- container-->

app/views/admin/users/_form.html.erb
<%= simple_form_for ([:admin, user]) do |f| %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :admin, label: "Is an admin?" %>S
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/users/index.html.erb
<div>
    <h1>Users</h1>
    
    <ul class="actions">
         <li><%= link_to "New User", new_admin_user_path, class: "new" %></li>
    </ul>
</div>

    <ul>
       <% @user.each do |user| %>
             <li><%= link_to user.email, [:admin, user] %></li>
       <% end %>
    </ul>

app/views/admin/users/new.html.erb
<div id="title"><h2>New User</h2> </div><!-- title-->
<%= render "form", user: @user %>

app/views/layouts/_footer.html.erb
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
	 <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> 
  <% if content_for?(:title) %>
      <%= yield(:title) %>
  <% else %> Ticketee
<% end %>
</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="container">
     <div id="logo" ><h1><%= link_to "Ticketee", root_path %></h1></div>
     <div id="user">
      <ul>
          <% unless user_signed_in? %>
           <li class="<%= "active" if current_page?("/users/sign_up") %>">
                  <%= link_to "Sign up", new_user_registration_path %>
          </li>
          <li class="<%= "active" if current_page?("/users/sign_in") %>">
               <%= link_to "Sign in", new_user_session_path %>
         </li>
         <% end %>
         <% if user_signed_in? %>
         <li>Signed in as <%= current_user.email %></li>
         <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
         <% end %>
      </ul> 
     </div><!-- users-->
  </div><!-- container -->
</header>	
<nav class="navigation">
    <div class="container">     
  <div class="nav-header">
    <div class="menuIcon">
      <a href="#menuExpand" id="#menuExpand">Menu</a>
    </div>

    <div class="menu">
      <ul>
        <li><%= link_to 'Home' , root_path %></li>
        <% admins_only do %>
             <li><%= link_to 'Admin',  admin_root_path %></li>
        <% end %>

      </ul>
    </div>
  </div>

</div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<%=render 'layouts/header'%>
 <div class="container">
  
   <% flash.each do |key, message| %>
      <div class="flash"><%= message %>
         <div id="close">X</div><!--close -->
      </div>
 <% end %>

 </div>
<%= yield %>
<%=render 'layouts/footer'%>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
 <% if project.errors.any? %>
    <div id="error_explanation">
              <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
       <ul>
           <% project.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
       </ul>
    </div>
<% end %>

<div class='label'>
           	 <%= f.label :name %>
           </div><!-- label -->

           <div id="prject_name_input">
                <%= f.text_field :name %>
           </div><!-- project_name input-->
       </div><!--project name-->

       <div id="description">
            <div class="label">
                <%= f.label :description %>
            </div><!-- description -->
            <div id="description_input">
                <%= f.text_field :description  %>
            </div><!-- description input -->

       </div><!-- description -->
      
    <div id="submit" >
       <%= f.submit %>
   </div><!-- submit -->
    
    
 
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class=" information_holder row ">
  	 <div id="about">
          <p> Edit project name or description for this current project.</p>
  	 </div><!-- About-->
<%= render "form", project: @project %>
</div><!-- information_holder -->
</div><!-- container -->

app/views/projects/index.html.erb
<% @title = "Home | Ticketee"%>
<div class="container">
  <div class=" information_holder row ">
    <!-- design look -->
    <div class="header">
    <h2 class='f-left'>Projects</h2>
    <% admins_only do %>
       <%= link_to "New Project", new_admin_project_path,:class=>'button_black f-left'%>
     <% end %>  
    </div><!-- header -->  
     <div class="m-holder">
<div id="projects">
<% @projects.each do |project| %>
         <ul>
              <li>
           	      <h2><%= link_to project.name, project %></h2>
                  <p><%= project.description %></p>
                  <span class='time_ago'> created <%= time_ago_in_words(project.created_at) %></span>
            </li>
         </ul>  
<% end %>
</div>

 </div><!-- holder-->     
 <!-- design look --> 
 </div><!-- information_holder -->

</div><!-- container -->

app/views/projects/show.html.erb
<div class="container">
    <% title(@project.name, "Projects") %>

    <div class=" information_holder ">
            	
    	<h2>Current Projects </h2>
    	  <div id="list_holder">
               <ul>
                   <li> 
                   	   <h3><%= @project.name %></h3>
                       <p id="dep"><%= @project.description %><p>
                       <span class='timeago'> created <%= time_ago_in_words(@project.created_at) %></span>

                       <% admins_only do %>
                            <div class="delete"><%= link_to "Delete Project", admin_project_path(@project), method:  :delete, data: { confirm: "Are you sure you want to delete this project?" },class: "delete" %>
                              
                      </div><!--delete-->
                      <% end %>

                   </li>

               </ul><!-- unorder list-->
               <ul class="tickets">
                     <% @project.tickets.each do |ticket| %>
                          <li>#<%= ticket.id %> - <%= link_to ticket.name, [@project, ticket] %></li>
                     <% end %>
                </ul>

    	  </div><!-- list_holder -->
    </div><!-- information_holder -->	
    <br>
    <%= link_to "Edit Project", edit_project_path(@project) , :class=>"edit_button" %>
    <%= link_to "New Ticket ",  new_project_ticket_path(@project) , :class=>"edit_button" %>
</div><!-- container-->

app/views/tickets/_form.html.erb
<%= simple_form_for([project, ticket]) do |f| %>


 
<div id="prject_name_input">
   <%= f.input :name %>
</div>
<%= f.text_area(:description , size:"68x10" ,placeholder:"Description") %>

<div id="submit">
    <%= f.button :submit, id: "submit" %>
</div>  
<% end %>

app/views/tickets/edit.html.erb
<div class="container">
   <div class=" information_holder ">
<div><h2> Edit Ticket <small><%= @project.name %></small></h2></div>
<%= render "form", project: @project, ticket: @ticket %>

 </div><!-- information_holder-->
</div><!-- container -->

app/views/tickets/new.html.erb
<div class="container">
   <div class=" information_holder ">

	<h2>New Ticket <small><%= @project.name %></small></h2>


	<%= render "form", project: @project, ticket: @ticket %>

  </div>
</div><!--container-->

app/views/tickets/show.html.erb
<div class="container">
   <div class=" information_holder ">
   	    <div id="ticket">
           <div class="project_name">
             <h2><%= @project.name %></h2>
          </div><!-- project name-->
        
        <div class="ticket_name">
              <h3><%= @ticket.name %></h3>
        </div><!-- ticket_name -->

        <table id="attributes">
              <tr>
                 <th>Author:</th>
                 <td><%= @ticket.author.email %></td>
             </tr>
              <tr>
                  <th>Created:</th>
                  <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
              </tr>
        </table>

<p id="show"><%= simple_format(@ticket.description) %></p>
<div><%= link_to "Edit Ticket", [:edit, @project, @ticket], class: "edit_button button_1" %></div>


<div><%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
data: { confirm: "Are you sure you want to delete this ticket?"},
class: "delete" %>
</div>
   </div><!-- information_holder-->
</div><!-- container -->